import {
  SiDjango,
  SiSpotify,
  SiYoutube,
  SiPython,
  SiReact,
  SiFastapi,
  SiJavascript,
  SiMongodb,
  SiRedux,
  SiTypescript,
  SiGithub,
  SiGitlab,
  SiVite,
  SiBulma,
  SiDocker,
  SiMysql,
} from "react-icons/si";

export const skills = [
  { icon: <SiReact size={80} />, name: "React" },
  { icon: <SiPython size={80} />, name: "Python" },
  { icon: <SiFastapi size={80} />, name: "FastAPI" },
  { icon: <SiJavascript size={80} />, name: "JavaScript" },
  { icon: <SiTypescript size={80} />, name: "TypeScript" },
  { icon: <SiVite size={80} />, name: "Vite" },
  { icon: <SiBulma size={80} />, name: "Bulma" },
  { icon: <SiDocker size={80} />, name: "Docker" },
  { icon: <SiDjango size={80} />, name: "Django" },
  { icon: <SiMongodb size={80} />, name: "MongoDB" },
  { icon: <SiMysql size={80} />, name: "MySQL" },
  { icon: <SiRedux size={80} />, name: "Redux" },
  { icon: <SiGithub size={80} />, name: "Github" },
  { icon: <SiGitlab size={80} />, name: "Gitlab" },
  { icon: <SiSpotify size={80} />, name: "Spotify" },
  { icon: <SiYoutube size={80} />, name: "YouTube" },
];
